export const sources = [
  {
    key: "blog-engineering",
    name: "Anthropic Engineering Blog",
    url: "https://www.anthropic.com/engineering",
    category: "core",
    scraperType: "blog-page",
    parseMode: "nextjs-rsc",
    basePath: "/engineering",
  },
  {
    key: "blog-news",
    name: "Anthropic News Blog",
    url: "https://www.anthropic.com/news",
    category: "core",
    scraperType: "blog-page",
    parseMode: "nextjs-rsc",
    basePath: "/news",
  },
  {
    key: "docs-release-notes",
    name: "Anthropic Docs Release Notes",
    url: "https://docs.anthropic.com/en/docs/about-claude/models",
    category: "core",
    scraperType: "docs-page",
    parseMode: "model-table",
  },
  {
    key: "claude-code-changelog",
    name: "Claude Code Changelog",
    url: "https://github.com/anthropics/claude-code/blob/main/CHANGELOG.md",
    category: "core",
    scraperType: "github-changelog",
    owner: "anthropics",
    repo: "claude-code",
    file: "CHANGELOG.md",
  },
  {
    key: "support-release-notes",
    name: "Anthropic Support Release Notes",
    url: "https://support.claude.com/en/articles/12138966-release-notes",
    category: "core",
    scraperType: "docs-page",
    parseMode: "intercom-article",
  },
  {
    key: "claude-code-releases",
    name: "Claude Code Releases",
    url: "https://github.com/anthropics/claude-code/releases",
    category: "core",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "claude-code",
  },
  {
    key: "npm-claude-code",
    name: "Claude Code npm Package",
    url: "https://www.npmjs.com/package/@anthropic-ai/claude-code",
    category: "core",
    scraperType: "npm-registry",
    packageName: "@anthropic-ai/claude-code",
  },
  {
    key: "agent-sdk-ts-changelog",
    name: "Agent SDK TypeScript Changelog",
    url: "https://github.com/anthropics/claude-agent-sdk-typescript/blob/main/CHANGELOG.md",
    category: "core",
    scraperType: "github-changelog",
    owner: "anthropics",
    repo: "claude-agent-sdk-typescript",
    file: "CHANGELOG.md",
  },
  {
    key: "agent-sdk-py-changelog",
    name: "Agent SDK Python Changelog",
    url: "https://github.com/anthropics/claude-agent-sdk-python/blob/main/CHANGELOG.md",
    category: "core",
    scraperType: "github-changelog",
    owner: "anthropics",
    repo: "claude-agent-sdk-python",
    file: "CHANGELOG.md",
  },
  {
    key: "api-sdk-ts-releases",
    name: "Anthropic SDK TypeScript Releases",
    url: "https://github.com/anthropics/anthropic-sdk-typescript/releases",
    category: "core",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "anthropic-sdk-typescript",
  },
  {
    key: "api-sdk-py-releases",
    name: "Anthropic SDK Python Releases",
    url: "https://github.com/anthropics/anthropic-sdk-python/releases",
    category: "core",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "anthropic-sdk-python",
  },
  {
    key: "claude-code-action",
    name: "Claude Code Action Releases",
    url: "https://github.com/anthropics/claude-code-action/releases",
    category: "extended",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "claude-code-action",
  },
  {
    key: "blog-alignment",
    name: "Anthropic Alignment Blog",
    url: "https://alignment.anthropic.com",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "distill",
  },
  {
    key: "blog-red-team",
    name: "Anthropic Red Team Blog",
    url: "https://red.anthropic.com",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "distill",
  },
  {
    key: "blog-research",
    name: "Anthropic Research Blog",
    url: "https://www.anthropic.com/research",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "nextjs-rsc",
    basePath: "/research",
  },
  {
    key: "blog-claude",
    name: "Anthropic Claude Blog",
    url: "https://claude.com/blog",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "webflow",
  },
  {
    key: "status-page",
    name: "Anthropic Status Page",
    url: "https://status.anthropic.com",
    category: "extended",
    scraperType: "status-page",
  },

  // ─── Community: GitHub commits (6) ───
  // Repos that ship via direct commits to main rather than tagged releases,
  // plus two third-party resource repos. All verified 2026-04-23: public,
  // default branch "main".
  {
    key: "gh-commits-cookbooks",
    name: "anthropics/claude-cookbooks (main commits)",
    url: "https://github.com/anthropics/claude-cookbooks",
    category: "community",
    scraperType: "github-commits",
    owner: "anthropics",
    repo: "claude-cookbooks",
    branch: "main",
    limit: 10,
    excludeBots: true,
  },
  {
    key: "gh-commits-skills",
    name: "anthropics/skills (main commits)",
    url: "https://github.com/anthropics/skills",
    category: "community",
    scraperType: "github-commits",
    owner: "anthropics",
    repo: "skills",
    branch: "main",
    limit: 10,
    excludeBots: true,
  },
  {
    key: "gh-commits-plugins-official",
    name: "anthropics/claude-plugins-official (main commits)",
    url: "https://github.com/anthropics/claude-plugins-official",
    category: "community",
    scraperType: "github-commits",
    owner: "anthropics",
    repo: "claude-plugins-official",
    branch: "main",
    limit: 10,
    excludeBots: true,
  },
  {
    key: "gh-commits-claude-code",
    name: "anthropics/claude-code (main commits, pre-release signal)",
    url: "https://github.com/anthropics/claude-code",
    category: "community",
    scraperType: "github-commits",
    owner: "anthropics",
    repo: "claude-code",
    branch: "main",
    limit: 10,
    excludeBots: true,
  },
  {
    key: "gh-commits-everything-claude-code",
    name: "affaan-m/everything-claude-code (community resource list)",
    url: "https://github.com/affaan-m/everything-claude-code",
    category: "community",
    scraperType: "github-commits",
    owner: "affaan-m",
    repo: "everything-claude-code",
    branch: "main",
    limit: 10,
    excludeBots: true,
  },
  {
    key: "gh-commits-antigravity-awesome-skills",
    name: "sickn33/antigravity-awesome-skills (community skills list)",
    url: "https://github.com/sickn33/antigravity-awesome-skills",
    category: "community",
    scraperType: "github-commits",
    owner: "sickn33",
    repo: "antigravity-awesome-skills",
    branch: "main",
    limit: 10,
    excludeBots: true,
  },

  // ─── Community: Reddit (5) ───
  {
    key: "reddit-claudecode",
    name: "r/ClaudeCode (top/day)",
    url: "https://www.reddit.com/r/ClaudeCode/",
    category: "community",
    scraperType: "reddit-subreddit",
    subreddit: "ClaudeCode",
    mode: "top",
    timeWindow: "day",
    limit: 15,
    minScore: 0,
  },
  {
    key: "reddit-claudeai",
    name: "r/ClaudeAI (top/day)",
    url: "https://www.reddit.com/r/ClaudeAI/",
    category: "community",
    scraperType: "reddit-subreddit",
    subreddit: "ClaudeAI",
    mode: "top",
    timeWindow: "day",
    limit: 10,
    minScore: 0,
  },
  {
    key: "reddit-claude",
    name: "r/claude (top/day)",
    url: "https://www.reddit.com/r/claude/",
    category: "community",
    scraperType: "reddit-subreddit",
    subreddit: "claude",
    mode: "top",
    timeWindow: "day",
    limit: 5,
    minScore: 0,
  },
  {
    key: "reddit-claudeskills",
    name: "r/claudeskills (top/day)",
    url: "https://www.reddit.com/r/claudeskills/",
    category: "community",
    scraperType: "reddit-subreddit",
    subreddit: "claudeskills",
    mode: "top",
    timeWindow: "day",
    limit: 10,
    minScore: 0,
  },
  // Claudeopus uses mode:"new" with minScore floor — lower-traffic sub where
  // top/day returns too few items. New + score floor catches substantive posts
  // without waiting end-of-day.
  {
    key: "reddit-claudeopus",
    name: "r/Claudeopus (new)",
    url: "https://www.reddit.com/r/Claudeopus/",
    category: "community",
    scraperType: "reddit-subreddit",
    subreddit: "Claudeopus",
    mode: "new",
    limit: 10,
    minScore: 20,
  },

  // ─── Community: Hacker News (1) ───
  {
    key: "hn-anthropic-mentions",
    name: "Hacker News — anthropic.com / claude.ai / claude.com",
    url: "https://hn.algolia.com/?q=anthropic.com+OR+claude.ai+OR+claude.com",
    category: "community",
    scraperType: "hn-algolia",
    query: "anthropic.com OR claude.ai OR claude.com",
    tags: "story",
    limit: 20,
  },

  // ─── Community: Twitter (8) ───
  // All handles verified active and on-topic (via live twitterapi.io API
  // call at implementation time). Scraper uses graceful-skip on missing
  // TWITTERAPI_IO_KEY so forks without the secret still run cleanly.
  {
    key: "twitter-anthropicai",
    name: "@AnthropicAI (official)",
    url: "https://x.com/AnthropicAI",
    category: "community",
    scraperType: "twitter-account",
    username: "AnthropicAI",
    limit: 10,
  },
  {
    key: "twitter-claudeai",
    name: "@claudeai (official)",
    url: "https://x.com/claudeai",
    category: "community",
    scraperType: "twitter-account",
    username: "claudeai",
    limit: 10,
  },
  {
    key: "twitter-claudedevs",
    name: "@ClaudeDevs",
    url: "https://x.com/ClaudeDevs",
    category: "community",
    scraperType: "twitter-account",
    username: "ClaudeDevs",
    limit: 10,
  },
  {
    key: "twitter-bcherny",
    name: "@bcherny (Boris Cherny, Anthropic)",
    url: "https://x.com/bcherny",
    category: "community",
    scraperType: "twitter-account",
    username: "bcherny",
    limit: 10,
  },
  {
    key: "twitter-theamolavasare",
    name: "@TheAmolAvasare (Amol Avasare)",
    url: "https://x.com/TheAmolAvasare",
    category: "community",
    scraperType: "twitter-account",
    username: "TheAmolAvasare",
    limit: 10,
  },
  {
    key: "twitter-felixrieseberg",
    name: "@felixrieseberg (Felix Rieseberg)",
    url: "https://x.com/felixrieseberg",
    category: "community",
    scraperType: "twitter-account",
    username: "felixrieseberg",
    limit: 10,
  },
  {
    key: "twitter-noahzweben",
    name: "@noahzweben (Noah Zweben)",
    url: "https://x.com/noahzweben",
    category: "community",
    scraperType: "twitter-account",
    username: "noahzweben",
    limit: 10,
  },
  {
    key: "twitter-janleike",
    name: "@janleike (Jan Leike, alignment)",
    url: "https://x.com/janleike",
    category: "community",
    scraperType: "twitter-account",
    username: "janleike",
    limit: 10,
  },
];
