export const sources = [
  {
    key: "blog-engineering",
    name: "Anthropic Engineering Blog",
    url: "https://www.anthropic.com/engineering",
    category: "core",
    scraperType: "blog-page",
    parseMode: "nextjs-rsc",
    basePath: "/engineering",
  },
  {
    key: "blog-news",
    name: "Anthropic News Blog",
    url: "https://www.anthropic.com/news",
    category: "core",
    scraperType: "blog-page",
    parseMode: "nextjs-rsc",
    basePath: "/news",
  },
  {
    key: "docs-release-notes",
    name: "Anthropic Docs Release Notes",
    url: "https://docs.anthropic.com/en/docs/about-claude/models",
    category: "core",
    scraperType: "docs-page",
    parseMode: "model-table",
  },
  {
    key: "claude-code-changelog",
    name: "Claude Code Changelog",
    url: "https://github.com/anthropics/claude-code/blob/main/CHANGELOG.md",
    category: "core",
    scraperType: "github-changelog",
    owner: "anthropics",
    repo: "claude-code",
    file: "CHANGELOG.md",
  },
  {
    key: "support-release-notes",
    name: "Anthropic Support Release Notes",
    url: "https://support.claude.com/en/articles/12138966-release-notes",
    category: "core",
    scraperType: "docs-page",
    parseMode: "intercom-article",
  },
  {
    key: "claude-code-releases",
    name: "Claude Code Releases",
    url: "https://github.com/anthropics/claude-code/releases",
    category: "core",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "claude-code",
  },
  {
    key: "npm-claude-code",
    name: "Claude Code npm Package",
    url: "https://www.npmjs.com/package/@anthropic-ai/claude-code",
    category: "core",
    scraperType: "npm-registry",
    packageName: "@anthropic-ai/claude-code",
  },
  {
    key: "agent-sdk-ts-changelog",
    name: "Agent SDK TypeScript Changelog",
    url: "https://github.com/anthropics/claude-agent-sdk-typescript/blob/main/CHANGELOG.md",
    category: "core",
    scraperType: "github-changelog",
    owner: "anthropics",
    repo: "claude-agent-sdk-typescript",
    file: "CHANGELOG.md",
  },
  {
    key: "agent-sdk-py-changelog",
    name: "Agent SDK Python Changelog",
    url: "https://github.com/anthropics/claude-agent-sdk-python/blob/main/CHANGELOG.md",
    category: "core",
    scraperType: "github-changelog",
    owner: "anthropics",
    repo: "claude-agent-sdk-python",
    file: "CHANGELOG.md",
  },
  {
    key: "api-sdk-ts-releases",
    name: "Anthropic SDK TypeScript Releases",
    url: "https://github.com/anthropics/anthropic-sdk-typescript/releases",
    category: "core",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "anthropic-sdk-typescript",
  },
  {
    key: "api-sdk-py-releases",
    name: "Anthropic SDK Python Releases",
    url: "https://github.com/anthropics/anthropic-sdk-python/releases",
    category: "core",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "anthropic-sdk-python",
  },
  {
    key: "claude-code-action",
    name: "Claude Code Action Releases",
    url: "https://github.com/anthropics/claude-code-action/releases",
    category: "extended",
    scraperType: "github-releases",
    owner: "anthropics",
    repo: "claude-code-action",
  },
  {
    key: "blog-alignment",
    name: "Anthropic Alignment Blog",
    url: "https://alignment.anthropic.com",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "distill",
  },
  {
    key: "blog-red-team",
    name: "Anthropic Red Team Blog",
    url: "https://red.anthropic.com",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "distill",
  },
  {
    key: "blog-research",
    name: "Anthropic Research Blog",
    url: "https://www.anthropic.com/research",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "nextjs-rsc",
    basePath: "/research",
  },
  {
    key: "blog-claude",
    name: "Anthropic Claude Blog",
    url: "https://claude.com/blog",
    category: "extended",
    scraperType: "blog-page",
    parseMode: "webflow",
  },
  {
    key: "status-page",
    name: "Anthropic Status Page",
    url: "https://status.anthropic.com",
    category: "extended",
    scraperType: "status-page",
  },
];
